################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
################################################################################
@endpoint = https://solveur-de-sudoku.herokuapp.com

### Test a board resolution (curl request that I got from the API-swagger-Docs when I used the "try it out" button)

curl -X 'POST' \
  'http://localhost:3000/api/board/solveBoard' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '[
  [
    0,
    2,
    0,
    0,
    0,
    2,
    0,
    4,
    0
  ],
  [
    2,
    0,
    0,
    0,
    0,
    8,
    0,
    0,
    0
  ],
  [
    3,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    8,
    0,
    6,
    9,
    0
  ],
  [
    0,
    0,
    0,
    0,
    0,
    4,
    0,
    0,
    1
  ],
  [
    0,
    6,
    0,
    0,
    0,
    0,
    8,
    0,
    7
  ],
  [
    0,
    0,
    0,
    0,
    0,
    7,
    5,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    2,
    0,
    4,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    2
  ]
]'
