################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
################################################################################
@endpoint = https://solveur-de-sudoku.herokuapp.com

### Test a board resolution
POST {{ endpoint }}/solveBoard
content-type: application/json

[
  [
    1,
    0,
    0,
    0,
    0,
    2,
    0,
    4,
    0
  ],
  [
    2,
    0,
    0,
    0,
    0,
    8,
    0,
    0,
    0
  ],
  [
    3,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    8,
    0,
    6,
    9,
    0
  ],
  [
    0,
    0,
    0,
    0,
    0,
    4,
    0,
    0,
    1
  ],
  [
    0,
    6,
    0,
    0,
    0,
    0,
    8,
    0,
    7
  ],
  [
    0,
    0,
    0,
    0,
    0,
    7,
    5,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    2,
    0,
    4,
    0,
    0
  ],
  [
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    2
  ]
]
